name: runconnect
description: RunConnect - A production-grade running community app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter:           # auth, database (Postgres), realtime, storage

  # Media
  image_picker:
  uuid:

  # Navigation
  go_router:

  # State Management
  flutter_bloc:

  flutter_dotenv:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
